Remove approved field from deposit model
AMPnet/integration-tests-ae pull request #106
Opened 2020-10-12 09:20 UTC by githinho

2020-10-12 11:22 UTC, filipdujmusic requested changes

2020-10-12 11:22 UTC, filipdujmusic commented on test/util/db.js
>              reference: 'reference',
extract to var

2020-10-12 11:32 UTC, githinho commented on test/util/db.js
>              reference: 'reference',
No way! It wouldn't be consistent with the rest of the code, see other inserts.

2020-10-13 10:54 UTC, filipdujmusic approved these changes

2020-10-13 10:54 UTC, merged